
<?php
/** @var \Attribute\Extention\Block\Edit $block*/
?>

<?php
 $editData = $block->edit();
?>
<form class="form contact"
      action="<?php echo $this->getUrl('disdata/index/save', ['_secure' => true]) . '?id=' . $editData->getId();?>"
      id="custom-form"
      method="post"
      data-hasrequired="<?php  echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
    <input type="hidden" name="cproduct_id" id="cproduct_id" value="0" />

    <fieldset class="fieldset">
        <legend class="legend"><span>Customer Data</span></legend><br />
        <div class="field firstname required">
            <label class="label" for="name">FirstName</label>
            <div class="control">
                <input name="firstname" id="firstname" value="<?php  echo $editData->getFirstname(); ?>" title="firstname" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>

        <div class="field lastname required">
            <label class="label" for="name">LastName</label>
            <div class="control">
                <input name="lastname" id="lastname" value="<?php  echo $editData->getLastname(); ?>" title="lastname" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>

        <div class="field email required">
            <label class="label" for="email">Email</span></label>
            <div class="control">
                <input name="email" id="email" value="<?php  echo $editData->getEmail(); ?>" title="Email" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
    </fieldset>

    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="Submit" class="action submit primary" id="custom_btn">
                Submit
            </button>
        </div>
    </div>
</form>

</div>

